### ISSUE TITLE
Holland User - Grant Issues

### ISSUE THREAD

**Issue by mlattanzi** [rackspace-cookbooks/stack_commons#118]
Currently failing to converge, running into issues where the 'super' grant for the holland user cannot be assigned due to specifying the database and not granting globally.

See: opscode-cookbooks/database#146

Worked with @martinb3 & @cybermerc to identify this issue

**Comment by cybermerc** [comment]
Going to test making a new customer only version of stack_commons to remove the mysql and mysql-multi pinning which requires a dated version of database

**Comment by cybermerc** [comment]
This issue was resolved.
