### ISSUE TITLE
Postgresql version is outdated in Centos65

### ISSUE THREAD

**Issue by marcoamorales** [rackspace-cookbooks/stack_commons#61]
```
       [2014-11-13T16:41:23+00:00] INFO: package[postgresql-server] installing postgresql-server-8.4.20-1.el6_5 from base repository
       
           - install version 8.4.20-1.el6_5 of package postgresql-server
```

Current version is 9.3, attributes are already there to install a specific version in `postgresql` cookbook, we just need to make sure to set them by default.

**Comment by cybermerc** [comment]
This is expected behavior that was not well documented. I have added a section in the README of pg-multi on how to override the default version.
