### ISSUE TITLE
Memcache IPTables rules

### ISSUE THREAD

**Issue by dexxtreme** [rackspace-cookbooks/stack_commons#70]
In the file stack_commons/blob/master/recipes/memcached.rb, there are "add_iptables_rule" calls that appear to allow access to Memcached to the world. This is a massive security risk due to the fact that there is no authentication for Memcache. This should be reconfigured to only allow access to the nodes in the environment. Also, does anyone actually connect to Memcache using UDP (or maybe check to see if "node['memcached']['udp_port']" is set to a usable value)?

**Comment by prometheanfire** [comment]
Sounds like it just needs to be changed to a search rule.

**Comment by cybermerc** [comment]
create https://github.com/rackspace-cookbooks/stack_commons/pull/91 to address this issue once merged this will be corrected
