### ISSUE TITLE
apache2 should not be a dependency

### ISSUE THREAD

**Issue by jujugrrr** [rackspace-cookbooks/stack_commons#82]
Stack_commons is not aware of apache2, and does nothing with it. so we should not have dependencies in the `metadata.rb`.

https://github.com/rackspace-cookbooks/stack_commons/blob/master/metadata.rb#L12

It's probably the same for uwsgi, nginx
https://github.com/rackspace-cookbooks/stack_commons/blob/master/metadata.rb#L25
https://github.com/rackspace-cookbooks/stack_commons/blob/master/metadata.rb#L34

**Comment by jujugrrr** [comment]
> it is a dependency because it is the minimum version that supports all the OS's we support in the dependant stacks. This was the common place to set that.

Each Stack is using/defining Apache based on its needs, maybe a Stack needs at least apache2 cookbook version 3 maybe another needs version < 3. Stack commons does nothing with apache2 cookbook. I don't think stack_common should be used as a version requirement stack (except if stack_common is actually doing the job (like for mysql))

**Comment by martinb3** [comment]
I agree that it seems weird to see the apache dependency here. Not all the stacks actually require it, and this stack doesn't require it (there's nothing de-duped that uses it).

**Comment by prometheanfire** [comment]
True, that doesn't get over the fact that it's the only version that supports the OS's we support though, even if we remove it here it needs to be the same in the dependant stacks.

**Comment by marcoamorales** [comment]
> Not all the stacks actually require it, and this stack doesn't require it 
+1
