### ISSUE TITLE
Resource naming issue with custom monitoring templates

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/stack_commons#88]
> no point to use a loop there https://github.com/rackspace-cookbooks/platformstack/blob/master/recipes/monitors.rb#L101-L115, because even if you have more than one https://github.com/rackspace-cookbooks/platformstack/blob/master/recipes/monitors.rb#L101, it will always recreate https://github.com/rackspace-cookbooks/platformstack/blob/master/recipes/monitors.rb#L106

We need to make the resource name and file names unique for each custom monitor.

/CC @jujugrrr

**Comment by jujugrrr** [comment]
@martinb3 Thank you for the issue, should we not put it in platformstack?

**Comment by martinb3** [comment]
@jujugrrr agreed, I'm just not paying attention :/
